version: '3.8'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    build: 
      context: .
      dockerfile: Dockerfile.ganache
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on: 
      - ganache
  web:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
